### ISSUE TITLE
[libs/movex-service] Add nx runner for `tsc` compiler 

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#101]
# Where

`libs/movex-service/project.json`

```json
{
   "name": "movex-service",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "libs/movex-service/src",
  "projectType": "library",
  "targets": {
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["libs/movex-service/**/*.ts"]
      }
    },
    ...
  },
}

```

# What

Add the following piece of code, **in the `targets` object just above the  `lint` property:**

```json
"tsc": {
      "executor": "nx:run-commands",
      "options": {
          "commands": [
              {
                  "command": "tsc --noEmit -p libs/movex-service/tsconfig.lib.json"
              }
          ]
      }
    }
```

# Why

To be able to run `npx nx tsc movex-service` or `npx nx tsc movex-service --watch` and add the typescript compiler command to CI.

This will be added as a Gtihub action so every new PR will also be checked for typescript compilation errors.

# Definition of done
- [ ] can run `npx nx tsc movex-service`
- [ ] can run `npx nx tsc movex-service --watch`

**Comment by Abhishek-Mallick** [comment]
@GabrielCTroia Could you please assign this to me

**Comment by techemmy** [comment]
@Abhishek-Mallick I've raised a PR for this already. @GabrielCTroia can I be assigned this task?
Also, @GabrielCTroia, I think there's a mistake in your description. I might be wrong

For the **Where**, do you mean `libs/movex/project.json` or `libs/movex-service/project.json`?

**Comment by techemmy** [comment]
I might have to correct the PR for that if it's a mistake?

**Comment by GabrielCTroia** [comment]
> @Abhishek-Mallick I've raised a PR for this already. @GabrielCTroia can I be assigned this task? Also, @GabrielCTroia, I think there's a mistake in your description. I might be wrong
> 
> For the **Where**, do you mean `libs/movex/project.json` or `libs/movex-service/project.json`?

Yes the mistake was right on! I corrected it in the description

**Comment by GabrielCTroia** [comment]
So @techemmy did you already work on this? I assigned to you the other related issue – https://github.com/movesthatmatter/movex/issues/100, and it would be fair to leave this one for @Abhishek-Mallick!

@Abhishek-Mallick do you still want it?

**Comment by Abhishek-Mallick** [comment]
Yup I can work on it

**Comment by techemmy** [comment]
Oh! I didn't see this message before now. @Abhishek-Mallick, please go ahead.

@GabrielCTroia you can cancel/close my PR on this.

**Comment by Abhishek-Mallick** [comment]
Hey @GabrielCTroia 

> To be able to run npx nx tsc movex-service or npx nx tsc movex-service --watch and add the typescript compiler command to CI. This will be added as a Gtihub action so every new PR will also be checked for typescript compilation errors.

Where do you want the tsc compiler cmd to be in the `project.json` itself?
like this after `build`
```
"compile": {
    "executor": "nx:run-commands",
    "options": {
      "commands": [
        {
          "command": "tsc"
        }
      ]
    }
  }
```

Or I was thinking as you are thinking of adding it to the workflow
There can be a separate `tsc-compiler.yml` with these configurations
```
name: TypeScript Compilation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: [16.x, 18.x]

      - name: Install Dependencies
        run: npm install

      - name: TypeScript Compilation
        run: npm run compile

      - name: Test
        run: npm test

```

Should I bring this up on a separate issue and for now just push the addition of `nx-runner` to `movex-service`
