### ISSUE TITLE
[project] Add Github Action for Typescript Compiler

### ISSUE THREAD

**Issue by GabrielCTroia** [movesthatmatter/movex#119]
# Where

`.github/workflows/tsc-compiler.yml`

# What

Add the following 

```yaml
name: TypeScript Compilation

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']


jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: [16.x]

      - name: Install Dependencies
        run: yarn install

      - name: TypeScript Compilation
        run: yarn tsc-all-libs
```

# Definition of done
- [ ] once merged github will be able to run the action on each new pull-request or merge to main

# Waits on Issues:
- https://github.com/movesthatmatter/movex/issues/117
- https://github.com/movesthatmatter/movex/issues/118
